// Code generated by protoc-gen-go. DO NOT EDIT.
// source: server_proto.proto

/*
Package server_proto is a generated protocol buffer package.

It is generated from these files:
	server_proto.proto

It has these top-level messages:
	CreateRoomRequest
	CreateRoomResponse
	EnterRoomRequest
	EnterRoomResponse
	DrawCardResponse
	DiscardRequest
	DiscardResponse
	Action
	ActionPrompt
	ActionSelectRequest
*/
package server_proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 客户端创建房间请求
type CreateRoomRequest struct {
	Uuid  string `protobuf:"bytes,1,opt,name=uuid" json:"uuid,omitempty"`
	Round int32  `protobuf:"varint,2,opt,name=round" json:"round,omitempty"`
}

func (m *CreateRoomRequest) Reset()                    { *m = CreateRoomRequest{} }
func (m *CreateRoomRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateRoomRequest) ProtoMessage()               {}
func (*CreateRoomRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CreateRoomRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *CreateRoomRequest) GetRound() int32 {
	if m != nil {
		return m.Round
	}
	return 0
}

// 服务器创建房间返回
type CreateRoomResponse struct {
	RoomId int32 `protobuf:"varint,1,opt,name=room_id,json=roomId" json:"room_id,omitempty"`
}

func (m *CreateRoomResponse) Reset()                    { *m = CreateRoomResponse{} }
func (m *CreateRoomResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateRoomResponse) ProtoMessage()               {}
func (*CreateRoomResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CreateRoomResponse) GetRoomId() int32 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

// 客户端进入房间请求
type EnterRoomRequest struct {
	RoomId int32 `protobuf:"varint,1,opt,name=room_id,json=roomId" json:"room_id,omitempty"`
}

func (m *EnterRoomRequest) Reset()                    { *m = EnterRoomRequest{} }
func (m *EnterRoomRequest) String() string            { return proto.CompactTextString(m) }
func (*EnterRoomRequest) ProtoMessage()               {}
func (*EnterRoomRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *EnterRoomRequest) GetRoomId() int32 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

// 服务器进入房间返回
type EnterRoomResponse struct {
	RoomId int32 `protobuf:"varint,1,opt,name=room_id,json=roomId" json:"room_id,omitempty"`
}

func (m *EnterRoomResponse) Reset()                    { *m = EnterRoomResponse{} }
func (m *EnterRoomResponse) String() string            { return proto.CompactTextString(m) }
func (*EnterRoomResponse) ProtoMessage()               {}
func (*EnterRoomResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *EnterRoomResponse) GetRoomId() int32 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

// 服务端抽牌提示
type DrawCardResponse struct {
	Card int32 `protobuf:"varint,1,opt,name=card" json:"card,omitempty"`
}

func (m *DrawCardResponse) Reset()                    { *m = DrawCardResponse{} }
func (m *DrawCardResponse) String() string            { return proto.CompactTextString(m) }
func (*DrawCardResponse) ProtoMessage()               {}
func (*DrawCardResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *DrawCardResponse) GetCard() int32 {
	if m != nil {
		return m.Card
	}
	return 0
}

// 客户端出牌请求
type DiscardRequest struct {
	Card int32 `protobuf:"varint,1,opt,name=card" json:"card,omitempty"`
}

func (m *DiscardRequest) Reset()                    { *m = DiscardRequest{} }
func (m *DiscardRequest) String() string            { return proto.CompactTextString(m) }
func (*DiscardRequest) ProtoMessage()               {}
func (*DiscardRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *DiscardRequest) GetCard() int32 {
	if m != nil {
		return m.Card
	}
	return 0
}

// 服务器出牌广播
type DiscardResponse struct {
	Uuid string `protobuf:"bytes,1,opt,name=uuid" json:"uuid,omitempty"`
	Card int32  `protobuf:"varint,2,opt,name=card" json:"card,omitempty"`
}

func (m *DiscardResponse) Reset()                    { *m = DiscardResponse{} }
func (m *DiscardResponse) String() string            { return proto.CompactTextString(m) }
func (*DiscardResponse) ProtoMessage()               {}
func (*DiscardResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *DiscardResponse) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *DiscardResponse) GetCard() int32 {
	if m != nil {
		return m.Card
	}
	return 0
}

// 服务器操作推送单位
type Action struct {
	SelectId   int32   `protobuf:"varint,1,opt,name=select_id,json=selectId" json:"select_id,omitempty"`
	ActionId   int32   `protobuf:"varint,2,opt,name=action_id,json=actionId" json:"action_id,omitempty"`
	ActionCard int32   `protobuf:"varint,3,opt,name=action_card,json=actionCard" json:"action_card,omitempty"`
	RefCards   []int32 `protobuf:"varint,4,rep,packed,name=ref_cards,json=refCards" json:"ref_cards,omitempty"`
	Weight     int32   `protobuf:"varint,5,opt,name=weight" json:"weight,omitempty"`
}

func (m *Action) Reset()                    { *m = Action{} }
func (m *Action) String() string            { return proto.CompactTextString(m) }
func (*Action) ProtoMessage()               {}
func (*Action) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Action) GetSelectId() int32 {
	if m != nil {
		return m.SelectId
	}
	return 0
}

func (m *Action) GetActionId() int32 {
	if m != nil {
		return m.ActionId
	}
	return 0
}

func (m *Action) GetActionCard() int32 {
	if m != nil {
		return m.ActionCard
	}
	return 0
}

func (m *Action) GetRefCards() []int32 {
	if m != nil {
		return m.RefCards
	}
	return nil
}

func (m *Action) GetWeight() int32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

// 服务器操作推送
type ActionPrompt struct {
	Action []*Action `protobuf:"bytes,1,rep,name=action" json:"action,omitempty"`
}

func (m *ActionPrompt) Reset()                    { *m = ActionPrompt{} }
func (m *ActionPrompt) String() string            { return proto.CompactTextString(m) }
func (*ActionPrompt) ProtoMessage()               {}
func (*ActionPrompt) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *ActionPrompt) GetAction() []*Action {
	if m != nil {
		return m.Action
	}
	return nil
}

// 客户端操作选择
type ActionSelectRequest struct {
	SelectId int32 `protobuf:"varint,1,opt,name=select_id,json=selectId" json:"select_id,omitempty"`
}

func (m *ActionSelectRequest) Reset()                    { *m = ActionSelectRequest{} }
func (m *ActionSelectRequest) String() string            { return proto.CompactTextString(m) }
func (*ActionSelectRequest) ProtoMessage()               {}
func (*ActionSelectRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *ActionSelectRequest) GetSelectId() int32 {
	if m != nil {
		return m.SelectId
	}
	return 0
}

func init() {
	proto.RegisterType((*CreateRoomRequest)(nil), "CreateRoomRequest")
	proto.RegisterType((*CreateRoomResponse)(nil), "CreateRoomResponse")
	proto.RegisterType((*EnterRoomRequest)(nil), "EnterRoomRequest")
	proto.RegisterType((*EnterRoomResponse)(nil), "EnterRoomResponse")
	proto.RegisterType((*DrawCardResponse)(nil), "DrawCardResponse")
	proto.RegisterType((*DiscardRequest)(nil), "DiscardRequest")
	proto.RegisterType((*DiscardResponse)(nil), "DiscardResponse")
	proto.RegisterType((*Action)(nil), "Action")
	proto.RegisterType((*ActionPrompt)(nil), "ActionPrompt")
	proto.RegisterType((*ActionSelectRequest)(nil), "ActionSelectRequest")
}

func init() { proto.RegisterFile("server_proto.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 324 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0xcd, 0x4a, 0xc3, 0x40,
	0x10, 0x26, 0x6d, 0x93, 0xb6, 0x53, 0xd1, 0x76, 0x15, 0x0d, 0x78, 0x68, 0x58, 0x44, 0x0a, 0x6a,
	0x85, 0x7a, 0xf2, 0xe0, 0x41, 0x5a, 0x0f, 0xbd, 0xc9, 0xfa, 0x00, 0x25, 0x66, 0xa7, 0x1a, 0xb0,
	0xd9, 0x3a, 0xbb, 0xb1, 0xaf, 0xe2, 0xe3, 0xca, 0xee, 0xf6, 0x27, 0x50, 0xd4, 0x4b, 0x98, 0xf9,
	0xfe, 0x32, 0x33, 0x2c, 0x30, 0x8d, 0xf4, 0x85, 0x34, 0x5b, 0x92, 0x32, 0x6a, 0xe8, 0xbe, 0xfc,
	0x01, 0x7a, 0x63, 0xc2, 0xd4, 0xa0, 0x50, 0x6a, 0x21, 0xf0, 0xb3, 0x44, 0x6d, 0x18, 0x83, 0x46,
	0x59, 0xe6, 0x32, 0x0e, 0x92, 0x60, 0xd0, 0x16, 0xae, 0x66, 0x27, 0x10, 0x92, 0x2a, 0x0b, 0x19,
	0xd7, 0x92, 0x60, 0x10, 0x0a, 0xdf, 0xf0, 0x1b, 0x60, 0x55, 0xbb, 0x5e, 0xaa, 0x42, 0x23, 0x3b,
	0x83, 0x26, 0x29, 0xb5, 0x98, 0xad, 0x23, 0x42, 0x11, 0xd9, 0x76, 0x2a, 0xf9, 0x15, 0x74, 0x9f,
	0x0a, 0x83, 0x54, 0xfd, 0xd9, 0xaf, 0xe2, 0x6b, 0xe8, 0x55, 0xc4, 0xff, 0x45, 0x5f, 0x42, 0x77,
	0x42, 0xe9, 0x6a, 0x9c, 0x92, 0xdc, 0x8a, 0x19, 0x34, 0xb2, 0x94, 0x36, 0x4a, 0x57, 0xf3, 0x0b,
	0x38, 0x9c, 0xe4, 0x3a, 0x73, 0xb2, 0xed, 0xb6, 0x7b, 0xaa, 0x7b, 0x38, 0xda, 0xaa, 0x76, 0x61,
	0x7b, 0x47, 0xd9, 0x58, 0x6b, 0x15, 0xeb, 0x77, 0x00, 0xd1, 0x63, 0x66, 0x72, 0x55, 0xb0, 0x73,
	0x68, 0x6b, 0xfc, 0xc0, 0xcc, 0xec, 0xc6, 0x6d, 0x79, 0x60, 0x2a, 0x2d, 0x99, 0x3a, 0x99, 0x25,
	0x7d, 0x40, 0xcb, 0x03, 0x53, 0xc9, 0xfa, 0xd0, 0x59, 0x93, 0x2e, 0xbf, 0xee, 0x68, 0xf0, 0x90,
	0x5d, 0xd1, 0xba, 0x09, 0xe7, 0x8e, 0xd5, 0x71, 0x23, 0xa9, 0x5b, 0x37, 0xe1, 0xdc, 0x72, 0x9a,
	0x9d, 0x42, 0xb4, 0xc2, 0xfc, 0xed, 0xdd, 0xc4, 0xa1, 0xbf, 0x91, 0xef, 0xf8, 0x2d, 0x1c, 0xf8,
	0xc9, 0x9e, 0x49, 0x2d, 0x96, 0x86, 0xf5, 0x21, 0xf2, 0x91, 0x71, 0x90, 0xd4, 0x07, 0x9d, 0x51,
	0x73, 0xe8, 0x69, 0xb1, 0x86, 0xf9, 0x08, 0x8e, 0x3d, 0xf2, 0xe2, 0xa6, 0xde, 0x5c, 0xec, 0xaf,
	0xbd, 0x5e, 0x23, 0xf7, 0xb0, 0xee, 0x7e, 0x02, 0x00, 0x00, 0xff, 0xff, 0x01, 0x41, 0x73, 0xf1,
	0x6e, 0x02, 0x00, 0x00,
}
