// Code generated by protoc-gen-go. DO NOT EDIT.
// source: server_proto.proto

/*
Package server_proto is a generated protocol buffer package.

It is generated from these files:
	server_proto.proto

It has these top-level messages:
	CreateRoomRequest
	CreateRoomResponse
	EnterRoomRequest
	EnterRoomResponse
*/
package server_proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateRoomRequest struct {
	Uuid  string `protobuf:"bytes,1,opt,name=uuid" json:"uuid,omitempty"`
	Round int32  `protobuf:"varint,2,opt,name=round" json:"round,omitempty"`
}

func (m *CreateRoomRequest) Reset()                    { *m = CreateRoomRequest{} }
func (m *CreateRoomRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateRoomRequest) ProtoMessage()               {}
func (*CreateRoomRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CreateRoomRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *CreateRoomRequest) GetRound() int32 {
	if m != nil {
		return m.Round
	}
	return 0
}

type CreateRoomResponse struct {
	RoomId int32 `protobuf:"varint,1,opt,name=room_id,json=roomId" json:"room_id,omitempty"`
}

func (m *CreateRoomResponse) Reset()                    { *m = CreateRoomResponse{} }
func (m *CreateRoomResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateRoomResponse) ProtoMessage()               {}
func (*CreateRoomResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CreateRoomResponse) GetRoomId() int32 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

type EnterRoomRequest struct {
	RoomId int32 `protobuf:"varint,1,opt,name=room_id,json=roomId" json:"room_id,omitempty"`
}

func (m *EnterRoomRequest) Reset()                    { *m = EnterRoomRequest{} }
func (m *EnterRoomRequest) String() string            { return proto.CompactTextString(m) }
func (*EnterRoomRequest) ProtoMessage()               {}
func (*EnterRoomRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *EnterRoomRequest) GetRoomId() int32 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

type EnterRoomResponse struct {
	RoomId int32 `protobuf:"varint,1,opt,name=room_id,json=roomId" json:"room_id,omitempty"`
}

func (m *EnterRoomResponse) Reset()                    { *m = EnterRoomResponse{} }
func (m *EnterRoomResponse) String() string            { return proto.CompactTextString(m) }
func (*EnterRoomResponse) ProtoMessage()               {}
func (*EnterRoomResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *EnterRoomResponse) GetRoomId() int32 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

func init() {
	proto.RegisterType((*CreateRoomRequest)(nil), "CreateRoomRequest")
	proto.RegisterType((*CreateRoomResponse)(nil), "CreateRoomResponse")
	proto.RegisterType((*EnterRoomRequest)(nil), "EnterRoomRequest")
	proto.RegisterType((*EnterRoomResponse)(nil), "EnterRoomResponse")
}

func init() { proto.RegisterFile("server_proto.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 152 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2a, 0x4e, 0x2d, 0x2a,
	0x4b, 0x2d, 0x8a, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x03, 0x93, 0x4a, 0xb6, 0x5c, 0x82, 0xce,
	0x45, 0xa9, 0x89, 0x25, 0xa9, 0x41, 0xf9, 0xf9, 0xb9, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25,
	0x42, 0x42, 0x5c, 0x2c, 0xa5, 0xa5, 0x99, 0x29, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x60,
	0xb6, 0x90, 0x08, 0x17, 0x6b, 0x51, 0x7e, 0x69, 0x5e, 0x8a, 0x04, 0x93, 0x02, 0xa3, 0x06, 0x6b,
	0x10, 0x84, 0xa3, 0xa4, 0xcb, 0x25, 0x84, 0xac, 0xbd, 0xb8, 0x20, 0x3f, 0xaf, 0x38, 0x55, 0x48,
	0x9c, 0x8b, 0xbd, 0x28, 0x3f, 0x3f, 0x37, 0x1e, 0x6a, 0x04, 0x6b, 0x10, 0x1b, 0x88, 0xeb, 0x99,
	0xa2, 0xa4, 0xcd, 0x25, 0xe0, 0x9a, 0x57, 0x92, 0x5a, 0x84, 0x6c, 0x19, 0x4e, 0xc5, 0x3a, 0x5c,
	0x82, 0x48, 0x8a, 0x09, 0x18, 0x9d, 0xc4, 0x06, 0xf6, 0x8f, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff,
	0xc8, 0x18, 0x65, 0xdc, 0xe5, 0x00, 0x00, 0x00,
}
